// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZTjqsCyUA9PYCNzFUC1HArklYYnqt1UU',
    appId: '1:205282340871:web:3fd65892eef79f41523aa2',
    messagingSenderId: '205282340871',
    projectId: 'aquasense-fd9f2',
    authDomain: 'aquasense-fd9f2.firebaseapp.com',
    databaseURL: 'https://aquasense-fd9f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquasense-fd9f2.firebasestorage.app',
    measurementId: 'G-31JYG3HJHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvfN_UHfPOjoasJLi15ZmxpbK9ANvWf8w',
    appId: '1:205282340871:android:00c42810c6176096523aa2',
    messagingSenderId: '205282340871',
    projectId: 'aquasense-fd9f2',
    databaseURL: 'https://aquasense-fd9f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquasense-fd9f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5o3V4OpVN-zvJd3oa7OkLJL7qDnJTqdc',
    appId: '1:205282340871:ios:36f98fae25a2025e523aa2',
    messagingSenderId: '205282340871',
    projectId: 'aquasense-fd9f2',
    databaseURL: 'https://aquasense-fd9f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquasense-fd9f2.firebasestorage.app',
    iosBundleId: 'com.example.aquasense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5o3V4OpVN-zvJd3oa7OkLJL7qDnJTqdc',
    appId: '1:205282340871:ios:36f98fae25a2025e523aa2',
    messagingSenderId: '205282340871',
    projectId: 'aquasense-fd9f2',
    databaseURL: 'https://aquasense-fd9f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquasense-fd9f2.firebasestorage.app',
    iosBundleId: 'com.example.aquasense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZTjqsCyUA9PYCNzFUC1HArklYYnqt1UU',
    appId: '1:205282340871:web:88740be833c14b54523aa2',
    messagingSenderId: '205282340871',
    projectId: 'aquasense-fd9f2',
    authDomain: 'aquasense-fd9f2.firebaseapp.com',
    databaseURL: 'https://aquasense-fd9f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquasense-fd9f2.firebasestorage.app',
    measurementId: 'G-0XS93NY0EY',
  );
}
